create table if not exists public.notification_preferences (
  user_id uuid primary key references auth.users (id) on delete cascade,
  send_hour_utc smallint not null default 9 check (send_hour_utc between 0 and 23),
  send_minute_utc smallint not null default 0 check (send_minute_utc between 0 and 59),
  preferred_time_local text not null default '09:00',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.notification_preferences enable row level security;

drop policy if exists "Users can read own notification preferences"
  on public.notification_preferences;

create policy "Users can read own notification preferences"
  on public.notification_preferences
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own notification preferences"
  on public.notification_preferences;

create policy "Users can insert own notification preferences"
  on public.notification_preferences
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own notification preferences"
  on public.notification_preferences;

create policy "Users can update own notification preferences"
  on public.notification_preferences
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.notification_dispatch_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  kind text not null check (kind in ('watering_due', 'replant_due', 'replant_week_before')),
  dispatch_date date not null,
  created_at timestamptz not null default now(),
  unique (user_id, kind, dispatch_date)
);

create index if not exists notification_dispatch_log_user_id_idx
  on public.notification_dispatch_log (user_id);

create index if not exists notification_dispatch_log_date_idx
  on public.notification_dispatch_log (dispatch_date);
